# Dari Extract ke Approximate Factor Models

Dalam sebuah factor model, korelasi di antara $n$ variabel, $x_1, \dots, x_n$, yang memiliki $T$ observasi, diasumsikan sepenuhnya disebabkan oleh beberapa, $r < n$, variabel laten yang tidak teramati, yang disebut sebagai factors. Hubungan antara variabel yang dapat diamati dan factors diasumsikan bersifat linear. Dengan demikian, setiap observasi $x_{it}$ dapat didekomposisi sebagai

\begin{equation}
    x_{it} = \mu_i + \lambda'_i f_t + \epsilon_{it},
\end{equation}

di mana $\mu_i$ adalah rata-rata dari $x_i$, $\lambda_i$ adalah vektor $r \times 1$, dan $\epsilon_{it}$ dan $f_t$ adalah dua proses yang tidak berkorelasi. Dengan demikian, untuk $i = 1, \dots, n$ dan $t = 1, \dots, T$, $x_{it}$ didekomposisi menjadi jumlah dari dua komponen yang tidak teramati dan saling ortogonal: komponen umum, $\chi_{it} = \lambda'_i f_t$, dan komponen idiosinkratik, $\xi_{it} = \mu_i + \epsilon_{it}$. Sementara factors menggerakkan komponen umum, komponen idiosinkratik digerakkan oleh karakteristik unik dari masing-masing variabel.

Korelasi antara $x_i$ dan $x_j$, dengan $j \neq i$, pada komponen idiosinkratik muncul dari karakteristik yang spesifik terhadap variabel $x_i$ masing-masing. Asumsi lebih lanjut yang ditempatkan pada dua komponen yang tidak teramati ini menghasilkan berbagai tipe factor models.

## Teknis Code

Sub-bagian ini menjelaskan konsep dasar factor model. Kita akan membuat contoh data sederhana dari factor model statis dasar:

$$
x_{it} = \mu_i + \lambda_i' f_t + \epsilon_{it}
$$

dengan asumsi sederhana bahwa $\mu_i = 0$ (data sudah di-de-mean), $\epsilon_{it}$ iid normal, dan $f_t$ iid normal.

**Langkah-langkah:**
1. Tetapkan dimensi: jumlah variabel $n$, jumlah faktor $r$, dan panjang deret waktu $T$.
2. Generate faktor $f_t$ sebagai deret acak $N(0, I)$.
3. Generate matriks loading $\Lambda$.
4. Generate error terms $\epsilon_{it}$.
5. Bentuk data $X$.


In [1]:
# Dari Extract ke Approximate Factor Models

import numpy as np

# Parameter
np.random.seed(123)
T = 200  # panjang deret waktu
n = 10   # jumlah variabel
r = 2    # jumlah faktor

# 1. Generate faktor f_t: matriks T x r
F = np.random.randn(T, r)  # f_t ~ N(0, I_r)

# 2. Generate loading matrix Lambda: n x r
Lambda = np.random.randn(n, r)  # loading faktor

# 3. Generate error terms epsilon: T x n
# Asumsikan error iid normal(0, sigma^2), di sini sigma^2 = 1
E = np.random.randn(T, n)

# 4. Bentuk data X: T x n
# Asumsikan data telah di-mean-kan, jadi mu_i = 0
X = F @ Lambda.T + E  # (T x r)*(r x n) = T x n, ditambah noise E

print("Contoh beberapa baris pertama data X:")
print(X[:5])



Contoh beberapa baris pertama data X:
[[-3.5743141   0.92538346  0.29507352  0.15215737  0.35240217 -0.8362032
   0.84847455 -1.28864083 -1.47603392 -1.70692833]
 [ 0.08508423  3.35322064 -1.28477552 -0.57435755 -0.36602887  0.81808755
  -0.62786398  1.2218745   2.14009004  3.84013921]
 [-0.59229023 -2.42881995  1.21953167  0.02400233  2.49649746  0.45894374
  -0.33126162 -3.14717875  1.04490788 -3.66212664]
 [-3.36607269  0.49040604 -1.80094034  3.89718839 -0.77835358 -0.96463799
   0.5036102  -0.12647437 -1.66687497  3.39840172]
 [ 2.36202915  1.96207047 -2.72800435 -2.23835008  0.29171327  0.03100084
   0.22990404  3.15036239  1.95375548  2.0596481 ]]


# Exact Factor Models

Exact factor model diperkenalkan oleh Spearman (1904). Model ini mengasumsikan bahwa komponen idiosinkratik tidak berkorelasi pada setiap lead dan lag sehingga $\xi_{it}$ dan $\xi_{ks}$ bersifat ortogonal secara mutual untuk semua $k \neq i$ dan sembarang $s$ dan $t$, sehingga semua korelasi di antara variabel yang dapat diamati didorong oleh factors. Model ini dapat ditulis sebagai

\begin{equation}
    x_{it} = \mu_i + \sum_{j=1}^{r} \lambda_{ij} f_{jt} + e_{it}, \quad i = 1, \dots, n, \, t = 1, \dots, T,
\end{equation}

di mana $f_{jt}$ dan $e_{it}$ adalah white noises yang ortogonal untuk setiap $i$ dan $j$; $e_{it}$ dan $e_{kt}$ adalah ortogonal untuk $k \neq i$; dan $\lambda_{ij}$ adalah loading dari faktor ke-$j$ pada variabel ke-$i$. Persamaan (1) juga dapat ditulis sebagai

\begin{equation}
    x_{it} = \mu_i + \lambda'_i f_t + e_{it}, \quad i = 1, \dots, n, \, t = 1, \dots, T,
\end{equation}

dengan $\lambda'_i = (\lambda_{i1}, \dots, \lambda_{ir})$ dan $f_t = (f_{1t}, \dots, f_{rt})'$. Komponen umum adalah $\chi_{it} = \sum_{j=1}^{r} \lambda_{ij} f_{jt}$, dan komponen idiosinkratik adalah $\xi_{it} = \mu_i + e_{it}$.

Dalam notasi matriks, dengan $x_t = (x_{1t}, \dots, x_{nt})'$, $f_t = (f_{1t}, \dots, f_{rt})'$, dan $e_t = (e_{1t}, \dots, e_{nt})'$, model dapat ditulis sebagai

\begin{equation}
    x_t = \mu + \Lambda f_t + e_t,
\end{equation}

di mana $\Lambda = (\lambda_1, \dots, \lambda_n)'$ adalah matriks $n \times r$ dengan full column rank (jika tidak, lebih sedikit factors akan cukup), dan matriks kovarian $e_t$ adalah diagonal karena komponen idiosinkratik diasumsikan tidak berkorelasi. Observasi yang tersedia untuk $t = 1, \dots, T$ dapat ditumpuk, dan Pers. (4) dapat ditulis ulang sebagai

\begin{equation}
    X = 1_T \otimes \mu' + F \Lambda' + E,
\end{equation}

di mana $X = (x_1, \dots, x_T)'$ adalah matriks $T \times n$, $F = (f_1, \dots, f_T)'$ adalah matriks $T \times r$, $E = (e_1, \dots, e_T)'$ adalah matriks $T \times n$, dan $1_T$ adalah vektor $T \times 1$ dengan komponen bernilai 1.

Meskipun asumsi utama di balik factor models adalah bahwa dua proses $f_t$ dan $e_t$ ortogonal satu sama lain, exact static factor model lebih lanjut mengasumsikan bahwa komponen idiosinkratik juga ortogonal satu sama lain, sehingga setiap korelasi antara variabel yang dapat diamati hanya disebabkan oleh factors umum.

Kedua asumsi ortogonalitas ini diperlukan untuk memastikan identifiabilitas model (lihat Anderson, 1984; Bartholomew, 1987). Perlu dicatat bahwa $f_t$ hanya didefinisikan hingga premultiplication oleh matriks invertibel $Q$ karena $f_t$ dapat digantikan oleh $Qf_t$ setiap kali $\Lambda$ digantikan oleh $\Lambda Q^{-1}$. Ini berarti bahwa hanya ruang yang masing-masing terbentang oleh $f_t$ dan $\Lambda$ yang didefinisikan secara unik. Masalah ketidakpastian factors ini harus diperhitungkan pada tahap estimasi.

Factor models telah diperkenalkan dalam ekonomi oleh Geweke (1977), Sargent dan Sims (1977), serta Engle dan Watson (1981). Para penulis ini menggeneralisasi model di atas untuk menangkap dinamika dalam data. Menggunakan notasi yang sama seperti pada Pers. (4), dynamic exact factor model dapat ditulis sebagai

\begin{equation}
    x_t = \mu + \Lambda_0 f_t + \Lambda_1 f_{t-1} + \cdots + \Lambda_s f_{t-s} + e_t,
\end{equation}

atau lebih ringkas:

\begin{equation}
    x_t = \mu + \Lambda(L)f_t + e_t,
\end{equation}

di mana $L$ adalah operator lag.

Dalam model ini, $f_t$ dan $e_t$ tidak lagi diasumsikan sebagai white noises, tetapi diizinkan untuk menjadi proses dinamis yang berkorelasi sendiri yang berkembang sesuai dengan $f_t = \Psi(L) u_t$ dan $e_t = \rho(L) \epsilon_t$, di mana vektor berdimensi $q$ dan $n$, masing-masing, $u_t$ dan $\epsilon_t$, mengandung kesalahan iid. Dimensi dari $f_t$ juga $q$, yang oleh karena itu disebut sebagai jumlah dari factors dinamis. Dalam kebanyakan literatur dynamic factor models, $f_t$ dan $e_t$ umumnya diasumsikan sebagai proses stasioner, sehingga jika diperlukan, variabel yang dapat diamati diproses ulang untuk menjadi stasioner.

Model ini memiliki representasi statis

\begin{equation}
    x_t = \mu + \Lambda F_t + e_t,
\end{equation}

dengan $F_t = (f_t', f_{t-1}', \dots, f_{t-s}')'$, vektor berdimensi $r = q(1+s)$ dari static factors, dan $\Lambda = (\Lambda_0, \Lambda_1, \dots, \Lambda_s)$, matriks $n \times r$ dari loading coefficients. Representasi dinamis dalam persamaan (1) dan persamaan (7) secara eksplisit menangkap ketergantungan variabel yang diamati pada lags dari factors, sementara representasi statis menyematkan dinamika tersebut secara implisit. Kedua bentuk ini mengarah pada metode estimasi yang berbeda yang akan dibahas di bawah ini.

Exact dynamic factor models mengasumsikan bahwa dimensi cross-sectional dari dataset, $n < T$, adalah terbatas, dan biasanya digunakan dengan sampel kecil, $n \ll T$. Ada dua alasan mengapa model-model ini diabaikan dalam kasus $n \to \infty$. Pertama, estimasi maximum likelihood, metode pilihan yang umum, memerlukan spesifikasi model parametrik penuh dan memberlakukan batasan praktis pada jumlah parameter yang dapat diestimasi seiring dengan $n \to \infty$. Kedua, seiring $n \to \infty$, beberapa asumsi yang tidak realistis yang diberlakukan pada exact factor models dapat dilonggarkan, dan approximate factor models dapat digunakan.

## Teknis Code
Exact factor model mengasumsikan bahwa semua korelasi antar variabel yang diamati dapat dijelaskan sepenuhnya oleh faktor, dan komponen idiosinkratik tidak berkorelasi silang. Kita akan mensimulasikan data serupa dengan poin di atas, namun menekankan bahwa $\epsilon_{it}$ adalah white noise yang ortogonal. Kemudian kita akan mencoba memperkirakan faktor dan loadings menggunakan PCA sederhana pada matriks data $X$.

**Langkah-langkah:**
1. Gunakan parameter yang sama atau baru.

2. Simulasikan data sesuai exact factor model (mirip dengan di atas, tapi kita tegaskan orthogonality).

3. Estimasi faktor dengan PCA:
   - Lakukan dekomposisi SVD pada $X$ (yang telah di-mean-kan).
   - Faktor diekstraksi sebagai komponen utama pertama sejumlah $r$.
   - Loadings diperoleh dari proyeksi data pada faktor yang diekstrak.



In [2]:
# Exact Factor Models

# Parameter model yang sama
np.random.seed(123)
T = 200
n = 10
r = 2

# Buat faktor dan loadings
F_true = np.random.randn(T, r)
Lambda_true = np.random.randn(n, r)

# Error yang ortogonal (iid)
E_exact = np.random.randn(T, n)  # iid normal(0,1), sudah ortogonal antar variabel

# Buat data X sesuai exact factor model
X_exact = F_true @ Lambda_true.T + E_exact

# Estimasi faktor dengan PCA:
X_centered = X_exact - X_exact.mean(axis=0)  # pastikan telah di-mean-kan
U, S, Vt = np.linalg.svd(X_centered, full_matrices=False)
# Skor faktor diperkirakan dari komponen utama
F_est = U[:, :r] * S[:r]  # Faktor perkiraan
Lambda_est = Vt[:r, :].T  # Loading perkiraan (transpos Vt)

print("Faktor sebenarnya vs faktor estimasi (hanya beberapa nilai):")
print("F_true[:5]:\n", F_true[:5])
print("F_est[:5]:\n", F_est[:5])

print("\nLoading sebenarnya vs loading estimasi:")
print("Lambda_true:\n", Lambda_true)
print("Lambda_est:\n", Lambda_est)


Faktor sebenarnya vs faktor estimasi (hanya beberapa nilai):
F_true[:5]:
 [[-1.0856306   0.99734545]
 [ 0.2829785  -1.50629471]
 [-0.57860025  1.65143654]
 [-2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404 ]]
F_est[:5]:
 [[-2.22946015  3.36190713]
 [ 4.17532709 -1.2614072 ]
 [-6.04740629  1.01159912]
 [ 3.48188514  5.03979763]
 [ 3.08565522 -4.50971241]]

Loading sebenarnya vs loading estimasi:
Lambda_true:
 [[ 1.53409029 -0.5299141 ]
 [-0.49097228 -1.30916531]
 [-0.00866047  0.97681298]
 [-1.75107035 -0.66585697]
 [ 0.0359405   0.85010288]
 [ 0.38287024  0.32546363]
 [-0.22431279  0.48187426]
 [ 1.01430388 -1.70899178]
 [ 0.7285354  -0.09875981]
 [-0.52998886 -2.44307579]]
Lambda_est:
 [[ 0.07882346 -0.56420952]
 [ 0.36823689  0.09955867]
 [-0.25590666  0.09541862]
 [ 0.27041838  0.59557484]
 [-0.23940855 -0.0263043 ]
 [-0.10874612 -0.16137797]
 [-0.15523794  0.09284121]
 [ 0.39086539 -0.4407942 ]
 [-0.00146604 -0.27549906]
 [ 0.6881535   0.04886807]]


# Approximate Factor Models
Seperti yang disebutkan sebelumnya, exact factor models bergantung pada asumsi yang sangat ketat bahwa tidak ada korelasi silang antara komponen idiosinkratik. Dalam dua makalah penting, Chamberlain (1983) dan Chamberlain dan Rothschild (1983) memperkenalkan approximate factor models dengan melonggarkan asumsi ini. Mereka mengizinkan komponen idiosinkratik untuk memiliki korelasi silang yang ringan dan memberikan serangkaian kondisi yang memastikan bahwa approximate factor models teridentifikasi secara asimtotik ketika $n \to \infty$.

Misalkan $x_{nt} = (x_{1t}, \dots, x_{nt})'$ adalah vektor yang berisi observasi ke-$t$ dari $n$ variabel pertama ketika $n \to \infty$, dan $\Sigma_n = \text{cov}(x_{nt})$ adalah matriks kovarian dari $x_t$. Dengan menyatakan $\lambda_1(A) \geq \lambda_2(A) \geq \dots \geq \lambda_n(A)$ sebagai eigenvalues yang terurut dari matriks simetris $A$ dengan ukuran $(n \times n)$, asumsi-asumsi yang mendasari approximate factor models adalah sebagai berikut:

1. [CR1] $\sup_n \lambda_r(\Sigma_n) = \infty$ (eigenvalues terbesar $r$ dari $\Sigma_n$ divergen)
2. [CR2] $\sup_n \lambda_{r+1}(\Sigma_n) < \infty$ (eigenvalues yang tersisa dari $\Sigma_n$ terbatas)
3. [CR3] $\inf_n \lambda_n(\Sigma_n) > 0$ ($\Sigma_n$ tidak mendekati singularitas)


Para penulis menunjukkan bahwa di bawah asumsi (CR1)–(CR3), terdapat dekomposisi unik $\Sigma_n = \Lambda_n \Lambda_n' + \Psi_n$, di mana $\Lambda_n$ adalah urutan matriks $n \times r$ dengan rank $r$ dan $\lambda_i(\Lambda_n \Lambda_n') \to \infty$ untuk semua $i = 1, \dots, r$, dan $\lambda_1(\Psi_n) < \infty$. Sebagai alternatif, $x_t$ dapat didekomposisi menggunakan sepasang proses vektor acak yang saling ortogonal, $f_t$ dan $e_{nt}$:

\begin{equation}
    x_{nt} = \mu_n + \Lambda_n f_t + e_{nt},
\end{equation}

dengan $\text{cov}(f_t) = I_r$ dan $\text{cov}(e_{nt}) = \Psi_n$, di mana $r$ common factors tersebar secara luas dalam arti bahwa jumlah variabel yang dipengaruhi oleh setiap faktor bertambah seiring dengan $n$, dan komponen idiosinkratik mungkin sedikit berkorelasi dengan kovarian yang terbatas.

Meskipun awalnya dikembangkan dalam literatur keuangan (lihat juga Connor \& Korajczyk, 1986, 1988, 1993), approximate static factor model masuk ke dalam makroekonometrika pada awal 2000-an (lihat misalnya Bai, 2003; Bai \& Ng, 2002; Stock \& Watson, 2002a, b). Makalah-makalah ini menggunakan asumsi yang analog dengan (CR1)–(CR3) untuk matriks kovarian dari factor loadings dan komponen idiosinkratik, tetapi mereka menambahkan asumsi pelengkap (yang bervariasi antar penulis karena alasan teknis) untuk mengakomodasi fakta bahwa data yang dikaji adalah time series yang berkorelasi sendiri. Model ini terutama digunakan dengan data yang stasioner atau telah diproses untuk menjadi stasioner, tetapi juga telah digunakan dalam kerangka kerja non-stasioner (lihat Bai, 2004; Bai \& Ng, 2004).

Serupa dengan exact dynamic factor models, approximate dynamic factor models juga bergantung pada persamaan yang menghubungkan deret yang dapat diamati dengan factors dan lags-nya, tetapi di sini komponen idiosinkratik dapat memiliki korelasi silang yang ringan, dan jumlah deret diasumsikan cenderung tak hingga. Model ini memiliki representasi dinamis sebagai berikut:

\begin{equation}
    x_{nt} = \mu_n + \Lambda_n(L) f_t + e_{nt}.
\end{equation}

dan representasi statis

\begin{equation}
    x_t^n = \mu_n + \Lambda_n F_t + e_t^n
\end{equation}

yang setara dengan (7) dan (8), masing-masing.

Dengan memusatkan deret yang diamati, $\mu_n$ dapat diset sama dengan nol. Demi kesederhanaan, di sisa bab ini kita akan mengasumsikan bahwa variabel-variabel sudah dipusatkan, dan kita juga menghilangkan sub- dan superscript $n$ pada $\Lambda_n$, $x_t^n$, dan $e_t^n$. Kita akan selalu mengasumsikan bahwa dalam exact factor models jumlah deret yang dipelajari terbatas, sedangkan dalam approximate factor models $n \to \infty$, dan serangkaian asumsi yang analog dengan (CR1)–(CR3)—tetapi sesuai dengan kerangka umum dari proses stasioner yang berkorelasi sendiri—terpenuhi.

## Teknis Code
Pada approximate factor models, komponen idiosinkratik diizinkan memiliki korelasi silang ringan. Kita akan membuat matriks kovarian idiosinkratik yang tidak diagonal sempurna, tetapi korelasi tetap kecil. Kemudian kita akan estimasi faktor menggunakan PCA dan menunjukkan bahwa meskipun terdapat korelasi ringan antar error, faktor dan loadings masih dapat diestimasi secara wajar, terutama saat $n$ besar.

**Langkah-langkah:**
1. Pilih $n$ lebih besar untuk menekankan konsep asimptotik ($n$ besar).
2. Buat faktor ($T \times r$) dan loadings ($n \times r$).
3. Buat matriks kovarian $\Psi$ untuk error yang sedikit berkorelasi. Misalnya, kita buat matriks kovarian idiosinkratik dengan korelasi kecil antar tetangga.
4. Generate error $E$ dari distribusi normal multivariat dengan kovarian $\Psi$.
5. Bentuk data $X$.
6. Lakukan PCA pada data $X$ untuk mengestimasi faktor.



In [3]:
# Approximate Factor Models

from scipy.stats import multivariate_normal

np.random.seed(123)
T = 500
n = 50
r = 3

# Buat faktor dan loadings
F_approx = np.random.randn(T, r)
Lambda_approx = np.random.randn(n, r)

# Buat matriks kovarian error Psi yang memiliki korelasi ringan
# Misalnya, korelasi yang cepat menurun dengan jarak antar variabel
correlation_strength = 0.1
indices = np.arange(n)
Psi = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        dist = abs(i-j)
        # korelasi mengecil saat jarak meningkat, mis: correlation_strength^(dist)
        Psi[i, j] = correlation_strength**dist

# Pastikan Psi positif-definit
# Dalam praktik, kita bisa langsung membuat matriks kovarian yang dijamin PD
# Tambahkan sedikit nilai diagonal agar dijamin PD
Psi = Psi + np.eye(n)*0.01

# Generate error E ~ N(0, Psi) untuk setiap t
E_approx = multivariate_normal.rvs(mean=np.zeros(n), cov=Psi, size=T)

# Bentuk data X
X_approx = F_approx @ Lambda_approx.T + E_approx

# Estimasi faktor dengan PCA
X_centered_approx = X_approx - X_approx.mean(axis=0)
U_approx, S_approx, Vt_approx = np.linalg.svd(X_centered_approx, full_matrices=False)
F_est_approx = U_approx[:, :r] * S_approx[:r]
Lambda_est_approx = Vt_approx[:r, :].T

print("Dimensi data:", X_approx.shape)
print("Approximate factor model: Faktor dan loadings telah diestimasi.")
print("Perbandingan dimensi:")
print("F_est_approx:", F_est_approx.shape)
print("Lambda_est_approx:", Lambda_est_approx.shape)


Dimensi data: (500, 50)
Approximate factor model: Faktor dan loadings telah diestimasi.
Perbandingan dimensi:
F_est_approx: (500, 3)
Lambda_est_approx: (50, 3)


# Maximum Likelihood Estimation untuk Small Factor Models
**Ide:**

- Kita memiliki model faktor statis kecil:

$$
x_t = \Lambda f_t + e_t
$$

dengan $\text{Var}(f_t) = I_r$ dan $\text{Var}(e_t) = \Sigma = \text{diag}(\sigma_1^2, \dots, \sigma_n^2)$.

- Observasi $(x_t)_{t=1}^T$ dianggap Gaussian. Maka $x_t \sim N(0, \Lambda \Lambda' + \Sigma)$.

- Likelihood (atau log-likelihood) dapat ditulis sebagai:

$$
\ell(\Lambda, \Sigma) = -\frac{T}{2} \log |\Lambda \Lambda' + \Sigma| - \frac{1}{2} \sum_{t=1}^T x_t' (\Lambda \Lambda' + \Sigma)^{-1} x_t.
$$

- Kita akan melakukan optimasi numerik (misalnya dengan `scipy.optimize.minimize`) untuk menemukan $\Lambda$ dan $\Sigma$ yang memaksimalkan likelihood.

**Langkah Sederhana:**

1. Buat data artifisial kecil (misalnya $n = 5$, $r = 2$, $T = 100$).
2. Definisikan fungsi log-likelihood.
3. Gunakan optimasi numerik untuk mendapatkan estimasi parameter.


In [4]:
# Maximum Likelihood Estimation untuk Small Factor Models
from scipy.optimize import minimize

# ==== Data Artifisial ====
np.random.seed(123)
T = 100
n = 5
r = 2

# True parameters
Lambda_true = np.array([[1.0, 0.5],
                        [0.4, 0.3],
                        [0.7, -0.2],
                        [0.2, 0.8],
                        [0.5, 0.5]])

Sigma_true_diag = np.array([0.2, 0.3, 0.25, 0.2, 0.3])
Sigma_true = np.diag(Sigma_true_diag)

F_true = np.random.randn(T, r)  # f_t ~ N(0,I)
E_true = np.random.randn(T, n) * np.sqrt(Sigma_true_diag)  # e_t
X = F_true @ Lambda_true.T + E_true

# ==== Definisi fungsi log-likelihood ====
# Param yang kita optimasi: elemen Lambda (n*r) dan diagonal Sigma (n)
# Kita akan vectorize param: first n*r elements = Lambda, next n elements = diag(Sigma)
def neg_log_likelihood(params, X, r):
    n = X.shape[1]
    T = X.shape[0]
    Lambda_flat = params[:n*r]
    Sigma_diag = params[n*r:]
    Lambda = Lambda_flat.reshape((n,r))
    Sigma = np.diag(Sigma_diag)

    Sigma_model = Lambda @ Lambda.T + Sigma
    # Inverse dan det Sigma_model
    # Pastikan Sigma_model invertibel
    try:
        inv_Sigma_model = np.linalg.inv(Sigma_model)
    except np.linalg.LinAlgError:
        return 1e10  # Penalti jika tak invertible

    sign, logdet = np.linalg.slogdet(Sigma_model)
    if sign <= 0:
        return 1e10  # Penalti jika tidak positif definit

    # Hitung log-likelihood
    ll = -0.5*T*logdet - 0.5*np.sum(X @ inv_Sigma_model * X) # x'Invx = sum((X inv)*X) secara elemen-wise
    return -ll  # karena kita minimize, maka negative log-likelihood

# Initial guess
Lambda_init = np.random.randn(n*r)
Sigma_init = np.ones(n)*0.5
params_init = np.concatenate([Lambda_init, Sigma_init])

res = minimize(neg_log_likelihood, params_init, args=(X, r), method='BFGS', options={'disp':False})
est_params = res.x
Lambda_est = est_params[:n*r].reshape((n,r))
Sigma_est = np.diag(est_params[n*r:])

print("Estimated Lambda:")
print(Lambda_est)
print("\nEstimated Sigma:")
print(Sigma_est)


Estimated Lambda:
[[ 1.206806    0.35875408]
 [ 0.53975854  0.09413363]
 [ 0.29728894  0.72735679]
 [ 0.74996179 -0.35444714]
 [ 0.84451944 -0.07301548]]

Estimated Sigma:
[[0.08030076 0.         0.         0.         0.        ]
 [0.         0.29886128 0.         0.         0.        ]
 [0.         0.         0.15001128 0.         0.        ]
 [0.         0.         0.         0.27012745 0.        ]
 [0.         0.         0.         0.         0.21981791]]


# Principal Component Analysis untuk Large Approximate Factor Models
1. Untuk approximate factor models dengan dimensi $n$ dan $T$ besar, PCA digunakan.
2. Kita generate data besar, lalu estimasi faktor dengan PCA.

In [5]:
# Principal Component Analysis untuk Large Approximate Factor Models
# Data besar
np.random.seed(123)
T = 500
n = 100
r = 3

F_large = np.random.randn(T, r)
Lambda_large = np.random.randn(n, r)
# Komponen idiosinkratik dengan sedikit korelasi (diabaikan di sini, pakai iid)
E_large = np.random.randn(T, n)*0.5
X_large = F_large @ Lambda_large.T + E_large

# Mean-center
Xc = X_large - X_large.mean(axis=0)

# PCA dengan SVD
U, S, Vt = np.linalg.svd(Xc, full_matrices=False)
F_est_pca = U[:, :r]*S[:r]  # T x r
Lambda_est_pca = Vt[:r, :].T  # n x r

print("PCA Factors shape:", F_est_pca.shape)
print("PCA Loadings shape:", Lambda_est_pca.shape)


PCA Factors shape: (500, 3)
PCA Loadings shape: (100, 3)


# Generalized Principal Component Analysis untuk Large Approximate Factor Models
**Ide:**

- GPCA menggunakan perkiraan matriks kovarian idiosinkratik $\Sigma$ dan melakukan "weighted PCA".

**Langkah sederhana:**

1. Estimasi faktor dengan PCA biasa.
2. Hitung residu $\hat{e}_t = x_t - \hat{\Lambda} \hat{f}_t$.
3. Estimasi $\hat{\Sigma}$ dari residu (misalnya diagonal dari varian residu).
4. Terapkan PCA dengan pembobot $\hat{\Sigma}^{-1}$.


In [8]:
# Generalized Principal Component Analysis untuk Large Approximate Factor Models
# Gunakan data X_large dari sebelumnya
Xc = X_large - X_large.mean(axis=0)
U, S, Vt = np.linalg.svd(Xc, full_matrices=False)
F_est_pca = U[:, :r]*S[:r]
Lambda_est_pca = Vt[:r, :].T

# Residual
E_hat = Xc - F_est_pca @ Lambda_est_pca.T

# Estimasi Sigma dari residual, misalnya diagonal:
Sigma_hat_diag = E_hat.var(axis=0)
Sigma_hat = np.diag(Sigma_hat_diag)

inv_Sigma_hat = np.diag(1/Sigma_hat_diag)

# Weighted PCA: Minimalkan (x_t - Lambda f_t)' Sigma^{-1} (x_t - Lambda f_t)
# Cara sederhana: transform data dengan sqrt(Sigma^{-1})
W = np.diag(1/np.sqrt(Sigma_hat_diag))
X_weighted = Xc @ W  # Sekarang noise relatif "sphere"

Uw, Sw, Vtw = np.linalg.svd(X_weighted, full_matrices=False)
F_est_gpca = Uw[:, :r]*Sw[:r]
Lambda_est_gpca = np.diag(1/np.sqrt(Sigma_hat_diag)) @ (Vtw[:r, :].T)

print("GPCA Factors shape:", F_est_gpca.shape)
print("GPCA Loadings shape:", Lambda_est_gpca.shape)


GPCA Factors shape: (500, 2)
GPCA Loadings shape: (100, 2)


# Two-Step dan Quasi-Maximum Likelihood Estimation untuk Large Approximate Factor Models

**Ide**:
1. Langkah 1: Estimasi faktor dan loadings dengan PCA.
2. Langkah 2: Estimasi model VAR untuk faktor, lalu masukkan model ke dalam kerangka state-space, dan gunakan Kalman smoother (misalnya dari library) untuk memperbaiki estimasi faktor.
3. QML: Memperlakukan model seolah exact (komponen idiosinkratik ortogonal) lalu menggunakan EM-Kalman filter. Di sini kami hanya berikan contoh sangat sederhana.

**Catatan**: Implementasi penuh QML dan EM algorithm untuk dynamic factor model cukup panjang. Di bawah ini hanya contoh ringkas dua langkah tanpa mendemonstrasikan EM secara penuh. Untuk EM dan Kalman Filter, biasanya digunakan library seperti statsmodels atau implementasi Kalman filter kustom.

In [7]:
# Two-Step dan Quasi-Maximum Likelihood Estimation untuk Large Approximate Factor Models
# Data simulasi untuk model dinamis sederhana
from numpy.linalg import inv

np.random.seed(123)
T = 300
n = 50
r = 2

# Buat faktor dengan VAR(1) misalnya: f_t = Phi f_{t-1} + u_t
Phi = np.array([[0.8, 0.0],
                [0.0, 0.5]])
f_dyn = np.zeros((T, r))
for t in range(1, T):
    f_dyn[t] = Phi @ f_dyn[t-1] + np.random.randn(r)*0.5

Lambda_dyn = np.random.randn(n, r)
E_dyn = np.random.randn(T, n)*0.5
X_dyn = f_dyn @ Lambda_dyn.T + E_dyn

# Step 1: PCA
Xc_dyn = X_dyn - X_dyn.mean(axis=0)
U_dyn, S_dyn, Vt_dyn = np.linalg.svd(Xc_dyn, full_matrices=False)
F_est_step1 = U_dyn[:, :r]*S_dyn[:r]  # Faktor awal dari PCA
Lambda_est_step1 = Vt_dyn[:r, :].T

# Estimasi VAR(1) pada faktor estimasi:
F_est_centered = F_est_step1 - F_est_step1.mean(axis=0)  # pastikan mean 0
F_reg_y = F_est_centered[1:]
F_reg_x = F_est_centered[:-1]
Phi_est = inv(F_reg_x.T@F_reg_x) @ (F_reg_x.T@F_reg_y)

# Step 2 (Two-step): Gunakan Kalman Filter/Smoother untuk state-space
# Contoh sederhana: state-space:
# f_t = Phi_est f_{t-1} + u_t
# x_t = Lambda_est_step1 f_t + noise
# Disini kita asumsikan Sigma diagonal dari step 1:
e_hat = Xc_dyn - F_est_step1 @ Lambda_est_step1.T
Sigma_est = np.diag(e_hat.var(axis=0))
Q = np.eye(r)*0.5  # kovarian u_t
R = Sigma_est

# Kalman Smoother (implementasi sederhana)
def kalman_smoother(Y, Lambda, Phi, Q, R):
    # Y: T x n
    # State: f_t, r-dim
    T_ = Y.shape[0]
    # Kalman filter pass
    f_predict = np.zeros((T_, r))
    P_predict = np.zeros((T_, r, r))
    f_update = np.zeros((T_, r))
    P_update = np.zeros((T_, r, r))

    # Init state
    f_update[0] = np.zeros(r)
    P_update[0] = np.eye(r)

    I = np.eye(r)
    for t in range(T_):
        # Prediction
        if t > 0:
            f_predict[t] = Phi @ f_update[t-1]
            P_predict[t] = Phi @ P_update[t-1] @ Phi.T + Q
        else:
            f_predict[t] = f_update[t]
            P_predict[t] = P_update[t]

        # Update
        y_t = Y[t]
        S = Lambda @ P_predict[t] @ Lambda.T + R
        K = P_predict[t] @ Lambda.T @ inv(S)
        f_update[t] = f_predict[t] + K@(y_t - Lambda@f_predict[t])
        P_update[t] = (I - K@Lambda)@P_predict[t]

    # RTS Smoother
    f_smooth = f_update.copy()
    P_smooth = P_update.copy()
    for t in range(T_-2, -1, -1):
        G = P_update[t] @ Phi.T @ inv(P_predict[t+1])
        f_smooth[t] = f_update[t] + G@(f_smooth[t+1]-f_predict[t+1])
        P_smooth[t] = P_update[t] + G@(P_smooth[t+1]-P_predict[t+1])@G.T

    return f_smooth

F_est_step2 = kalman_smoother(Xc_dyn, Lambda_est_step1, Phi_est, Q, R)

print("Faktor awal (PCA) vs faktor setelah two-step:")
print("PCA faktor (first 5):\n", F_est_step1[:5])
print("Kalman smoother faktor (first 5):\n", F_est_step2[:5])


Faktor awal (PCA) vs faktor setelah two-step:
PCA faktor (first 5):
 [[-0.19720047  0.57116056]
 [ 4.8531812   2.60227222]
 [ 1.14466229 -3.18138549]
 [ 5.79571849  2.85042253]
 [10.40497495 -1.21668138]]
Kalman smoother faktor (first 5):
 [[ 0.64721564  0.6851831 ]
 [ 3.47820434  1.58976559]
 [ 2.3889306  -1.7241132 ]
 [ 5.52918791  1.43273709]
 [ 8.15817729 -0.94895246]]
